services:
  # 1. База данных TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: iiot_db
    ports:
      - "5432:5432"
    # Добавляем проверку здоровья (healthcheck), чтобы бэкенд ждал запуска базы
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d iiot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. MQTT Брокер
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 3. Наш Python Бэкенд
  backend:
    build: .  # Указывает Docker'у собрать образ из Dockerfile в текущей папке
    ports:
      - "8000:8000"
    environment:
      # Переопределяем переменные окружения, чтобы бэкенд искал соседей по сети Docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secretpassword
      - DB_NAME=iiot_db
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      postgres:
        condition: service_healthy # Бэкенд запустится только когда база ответит "я готова"
      mosquitto:
        condition: service_started
